# Generated by Django 3.2.16 on 2022-11-27 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, max_length=1000, null=True)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('start_day', models.CharField(blank=True, max_length=100, null=True)),
                ('end_day', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_users', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('غير منجزة', 'غير منجزة'), ('بأنتظار الموافقة', 'بأنتظار الموافقة'), ('منجزة', 'منجزة')], default='غير منجزة', max_length=100)),
                ('rate', models.SmallIntegerField(default=0)),
                ('received', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ManyToManyField(related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('account', models.CharField(choices=[('ادمن', 'ادمن'), ('محرر', 'محرر'), ('مستخدم', 'مستخدم')], default='مستخدم', max_length=100)),
                ('behaviour', models.IntegerField(default=0)),
                ('compliance', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received', models.BooleanField(default=False)),
                ('emps', models.ManyToManyField(related_name='emps', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
