# Generated by Django 3.2.16 on 2022-10-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.CharField(choices=[('ادمن', 'ادمن'), ('محرر', 'محرر'), ('مستخدم', 'مستخدم')], default='مستخدم', max_length=100),
        ),
    ]
