# Generated by Django 3.2.16 on 2022-10-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20221029_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
