# Generated by Django 3.2.16 on 2022-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_task_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rate',
            field=models.SmallIntegerField(default=0),
        ),
    ]
